version: '3'
services:

  log_producer:
    image: log_producer:latest

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

 # spark:
 #   image:

  cassandra:
    image: bitnami/cassandra:latest
    ports:
      - '7000:7000'
    volumes:
      - cassandra_data:/bitnami

  hdfs:
    image: sequenceiq/hadoop-docker
    ports:
      - '50010:50010'
      - '50020:50020'
      - '50070:50070'
      - '50075:50075'
      - '50090:50090'
      - '8020;8020'
      - '9000:9000'

  hadoop-namenode:
    image: 'uhopper/hadoop-namenode'
    hostname: hadoop-namenode
    ports:
      - "8020:8020"
      - '50070:50070'
    volumes:
      - hdfs_namenode:/var/hadoop
    environment:
      - CLUSTER_NAME=hadoop-sandbox
      - HDFS_CONF_dfs_replication=1

  hadoop-datanode:
    image: "uhopper/hadoop-datanode"
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:8020
      - CLUSTER_NAME=hadoop-sandbox
      - HDFS_CONF_dfs_replication=1
    ports:
      - 50075:50075
    volumes:
      - hdfs_datanode:/var/hadoop
    depends_on:
      - hadoop_namenode

volumes:
  cassandra_data:
  hdfs_datanode:
  hdfs_namenode:
